name: ktlint

on:
    pull_request:
        branches:
            - develop

jobs:
    ktlint:
        name: Check Code Quality
        runs-on: ubuntu-latest

        steps:
            - name: Clone repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - name: Setup JDK
              uses: actions/setup-java@v2
              with:
                  java-version: '11'

            - name: Run ktlint
              run: |
                  ./gradlew ktlintCheck --daemon --parallel --configure-on-demand
